### ISSUE TITLE
verse.sty incompatibility

### ISSUE THREAD

**Issue by YellowJacketLinux** [latex3/tagging-project#49] opened 2023-12-12 10:02 UTC
This may already be known, but when I use `testphase=phase-III` I get the following error:

    [...]
    Patching \page@sofar for tagging
    (/opt/texlive/2023/texmf-dist/tex/latex/hyphenat/hyphenat.sty)
    (/opt/texlive/2023/texmf-dist/tex/latex/verse/verse.sty
    ! LaTeX Error: Command \theHpoemline already defined.
                   Or name \end... illegal, see p.192 of the manual.
    
    See the LaTeX manual or LaTeX Companion for explanation.
    Type  H <return>  for immediate help.
     ...                                              
                                                      
    l.34 ...ne}{\arabic{verse@envctr}.\arabic{poemline}}

However `testphase=phase-II` works fine.

I am loading `verse.sty` which is probably why.

I'm guessing it's `verse.sty` that actually needs to be fixed, but thought I'd mention the incompatibility here.

**Comment by wspr** [comment] 2024-02-12 12:36
@u-fischer  — I have sent an update to CTAN with your suggested fix... fingers are rusty but the build.lua file worked a treat!!

**Comment by FrankMittelbach** [comment] 2024-03-19 21:44
> There's supposed to be a blank line before the punch-line but because the tagging seems to interfere with the package, the blank line is gone and the exclamation make gets typeset before the punch-line.

thought I had already made a remark on this, but I can't find it. Anyway, the issue is that the definition for the verse environment is overwritten at begin document by the tagging code. the simplest solution is therefore to repeat it afterwards. However, doing that showed an error in the block tagging code which needs fixing first. So bottom line this will get corrected (with some firstaid for verse) during the next days and from there will make it into the next -dev release.

**Comment by u-fischer** [comment] 2024-07-05 14:46
The `\theHpoemline` error has been fixed in verse.sty. For the problem with the `!` there is a fix in the firstaid module, it compiles fine with

~~~~
\DocumentMetadata{
 uncompress,
 pdfversion=1.7,
 lang=en-US,
 testphase={phase-III,firstaid}
}
\documentclass{article}
\usepackage{fontspec}
\setromanfont{TeX Gyre Termes}
\usepackage{verse}
\begin{document}
\begin{verse}
I took a walk down the street.\\
\hspace{1em}One house was numbered `64k'\\
\hspace{1em}One house was numbered `128k'\\
\hspace{1em}One house was numbered `256k'\\
\hspace{1em}One house was numbered `512k'\\
\hspace{1em}One house was numbered `1M'\\!
It was a trip down memory lane\ldots{}
\end{verse}
\end{document}
~~~~

So I'm closing the issue.

**Closed by u-fischer** 2024-07-05 14:46 UTC
Labels: bug, currently incompatible package or class, fixed in branch
