### ISSUE TITLE
Longtable, colortbl and tags clash

### ISSUE THREAD

**Issue by DavidEGx** [latex3/tagging-project#90] opened 2024-07-02 09:22 UTC
Hi,

Got this latex code:

```latex
\DocumentMetadata{
  lang        = en,
  pdfversion  = 2.0,
  pdfstandard = ua-2,
  testphase   = {phase-III, table}
}

\documentclass[10pt]{article}

\usepackage{longtable}
\usepackage[table]{xcolor}

\begin{document}

\begin{longtable}{ p{0.3\textwidth} p{0.3\textwidth} }
\hline Row 1 & 105 \\
\end{longtable}

\end{document}                                        
```

Then I run:
```bash
$ lualatex test.tex
```
and got:

```bash
...
(/opt/texlive/2024/texmf-dist/tex/latex/pdfmanagement-testphase/xcolor-patches-
tmp-ltx.sty) (/opt/texlive/2024/texmf-dist/tex/latex/colortbl/colortbl.sty)
(./latest.aux) (/opt/texlive/2024/texmf-dist/tex/latex/base/ts1cmr.fd)
(/opt/texlive/2024/texmf-dist/tex/context/base/mkii/supp-pdf.mkii
[Loading MPS to PDF converter (version 2006.09.02).]
)
! Undefined control sequence.
<argument> \ERRORtbl 
          /row
l.18 \end
       {longtable}
```

Same thing using `xelatex`.

Either removing:

* `table` in line 5.
* `\usepackage[table]{xcolor}` in line 11.
* `\hline` in line 16.

Make it work without any issue.

**Comment by u-fischer** [comment] 2024-07-02 22:45
colortbl overwrites the \hline definition and this breaks the tagging code.

It seems to work if one handles the multispan similar to the booktabs firstaid, but there aren't many testfiles around.

~~~~
\DocumentMetadata{
  lang        = en,
  pdfversion  = 2.0,
  pdfstandard = ua-2,
  testphase   = {phase-III, table},
}

\documentclass[10pt]{article}

\usepackage{longtable}
\usepackage{colortbl}

\begin{document}
\makeatletter
\ExplSyntaxOn
    \def\LT@@hline{%
      \ifx\LT@next\hline
        \global\let\LT@next\@gobble
        \ifx\CT@drsc@\relax
          \gdef\CT@LT@sep{%
            \noalign{\penalty-\@medpenalty\vskip\doublerulesep}}%
        \else
          \gdef\CT@LT@sep{%
            \multispan\LT@cols{%
              \tag_mc_begin:n{artifact}
              \CT@drsc@\leaders\hrule\@height\doublerulesep\hfill
              \tag_mc_end: \int_gdecr:N \g__tbl_row_int 
            }\cr}%
        \fi
      \else
        \global\let\LT@next\empty
        \gdef\CT@LT@sep{%
          \noalign{\penalty-\@lowpenalty\vskip-\arrayrulewidth}}%
      \fi
      \ifnum0=`{\fi}%
      \multispan\LT@cols
       {\tag_mc_begin:n{artifact}
        \CT@arc@\leaders\hrule\@height\arrayrulewidth\hfill
        \tag_mc_end: \int_gdecr:N \g__tbl_row_int 
       }\cr
      \CT@LT@sep
      \multispan\LT@cols
       {\tag_mc_begin:n{artifact}
        \CT@arc@\leaders\hrule\@height\arrayrulewidth\hfill
        \tag_mc_end: \int_gdecr:N \g__tbl_row_int 
       }\cr
      \noalign{\penalty\@M}%
      \LT@next}

\ExplSyntaxOff

\begin{longtable}{ p{3cm}p{3cm}}
\hline 
Row 1 & 105 \\
\hline\hline 
\end{longtable}

\end{document}              
~~~~

**Comment by FrankMittelbach** [comment] 2024-07-04 09:07
so the cause is xcolor loading colrtbl, right? so we should probably change the issue title to mention colortbl and then mark for now as not fully compatible

**Comment by davidcarlisle** [comment] 2024-07-06 19:42
This should be fixed by the colortbl update in the above comment, I'll release that to ctan today

**Closed** 2024-07-06 19:43 UTC
Labels: currently incompatible package or class
